# Generated by Django 3.0.7 on 2020-07-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('smallPrice', models.FloatField()),
                ('largePrice', models.FloatField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='orders.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='topping',
            name='dishes',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.AddField(
            model_name='topping',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Product'),
        ),
    ]
