# Generated by Django 3.0.7 on 2020-07-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_toppings',
            field=models.IntegerField(default=0),
        ),
    ]
