# Generated by Django 3.0.7 on 2020-07-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_product_max_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField(default=0, editable=False)),
                ('items', models.ManyToManyField(related_name='orders', to='orders.CartItem')),
            ],
        ),
    ]
